version: "3.9"

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    ports:
      - "8000:8000"
    command: >
      --host 0.0.0.0
      --port 8000
      --model Qwen/Qwen3-0.6B-Base
    volumes:
      - /media/hdddisk/yisheng/replicate/sft_capybara:/models
    deploy: {}   # remove deploy.resources if not in Swarm
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
      - OPENAI_API_KEY=none
    depends_on:
      - vllm

