# Model 
model_name_or_path: gongyisheng/Qwen2.5-Math-1.5B-RoPE-300k

# Dataset 
dataset_name: open-r1/Mixture-of-Thoughts
dataset_config: all

# Tokenizer 
eos_token: '<|im_end|>'
dataset_num_proc: 8

# Training 
learning_rate: 4.0e-5
num_train_epochs: 5
max_length: 32768
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
bf16: true
warmup_ratio: 0.1
weight_decay: 0.01

# Wandb 
report_to: wandb
wandb_project: openr1
wandb_run_name: qwen2.5-math-1.5b-sft

# Output 
output_dir: /media/hdddisk/yisheng/replicate/openr1/qwen2.5-math-1.5b-sft
