version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis-7.2
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis-network
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    restart: always
    ports:
      - "9121:9121"
    networks:
      - redis-network
    command:
      - '--redis.addr=redis://redis-7.2:6379'

networks:
  redis-network:
    driver: bridge