environment: development

# API Keys
openai_api_key: 

# LinkedIn API Configuration
linkedin:
  client_id: 
  client_sec
  api_base_url: "https://api.linkedin.com/v2"
  auth_url: "https://www.linkedin.com/oauth/v2/accessToken"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000

# CORS Configuration
cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"] 