import sys
import time

import mysql.connector

from config import db_cred

supported_table = {
    "5": "qbqBaDEUPtVxudqspDncYswuJReaLenIRaazDUrNuvoJOfpTfrJOfnJWQZZuAklIMSKytNsiIOPBXvmLlanDTeBVaxEkeilJdnOFpMcXGQLesGYahIUpbuwpkloZneWSvUrCbfGhzAWFqrtxPoITZgdZvTrGFGrYMDRHtzDIrazFVZOFHrZxylgEwNRoHdvwDIXeWuJxDpaCsqSjgQDhEjIMumVPtySerRLnlQjbVtlIJoqqslwZwRZnIbFCHaCFMeSwOYXKPCjZiQfHucMfgpZmVJXJzbEKxnSbOrBwzeXwWYNCvjWgiIKKXLEygZlncrKfEPuwqBcsSYmvPQjwsufvVTkHUVrGcAEvxCUziRvXtcOCfQHcnlaXcBdNfTcQMXwCcUeUgVpohdxaagcjAGgybOgjQPMFraipkrBgcVkOQjXVzaRyQTZvksmUxTPKuMYhYHSgdYvtSwhbKUEQiURkTBuZqfrjcicTrovimVdLrcBhbgqjLIFkYsogfrSSBhDOAHImynXMxNjeFtNVbWFxlJTZycWxkyxMomphFzFVguzYbmcYiRgNyuPfBOXdgemLcLgCTcCXiEOARhmOEGwERFQyLvwCVrwGNVXGHAwVPrktEqjZQXkjcNvXmvjOcJnrDHwHLCVTWIJrReGvjByLjVWrGLdlTvCquSxuzIwyRzPScirvYiodNNjROjRmFvwvvxClCmlhoXigVdQQOejVcHrEeBhtbLnLCgezWGgROxWVfHcVENbDWFSvnFJI",
    "25": "hlGsVpkyjoGGknKuJZFOZWELpYLcFrqNXyJPLqOYXZxsjZlIhFoFszULspPkcNyQjXfKLPgPftQbOqmLppZvJQgYnPlUIsesMbWWocQJyVJhUuypDlBWLpSpYnHUvYPpSaIqrPkFPttmADtPMAFperwKhTthOAqtFrKrmrccoyoPsjYuHrYnuSLRVlcXNbTxtIOCxJuKvXYXPqpLPlebbQIAZIGQWWUibGrDeVCImmntuWrwPPLwahnXWXofHYxzbbpCSGeBREkuGIBgTjoolxTRhyupArvWtpbzLbQwDctnZXmfmMRZlSnWDUOgjAUfopQPVWgdxnXfWjxZUVXCePfsuOkBDsXOHxbrebtkclpnxVbGORAhzPMkGYzKxPDRjSOdtASjzvuxJASaUhGLzeCWqsQmrqdTBUqNTabyRbAiYaowQJVuwbSkVDtSlhuhqVdfaDgxfjoqlMduEFnCKWzKmVpNVJNfhhUdTrEqQxjqPfvXRKzUJhVZIQptjLTNYfszwLDkTPboNgnMzWTQOcXYEgyIWgeUUZTaLFyiYXqqCvdUCtWTautiMGUdJrrcqRJHtBBqtBTZOFGoJmayHvCklsfOnqRCuQiLuCqzBZWNwmflCqIMIOyppADHuaSArKARTggERvfLnxHwzQVRdhtGdHtSDKqmQcorIaapNTDcasxkHVzIMzgRTvdEguEiHReRymfGHvwDixgJHNUFMLUSqdbmrotSrEwJxRsWzCvMMZlDmsIiQLxLuifGBeLN",
    "125": "DmaQhjxogYHXsgCSDBxjeuONvtvgDepHxBmOQoDVwqZfnMENQTIoORMrWaPPeLMBCUQrWfcmOGqUKTQqXSXmAALpXXoezyMLnLBjykHoemkslYwZuAlJNwOWCdNHRUeAJcdYAGInyPEjTCZzFutDnwQVTQGGKEKHAsaAfYTUpxojmqdzisWjbcxUrZrRPxRLvFsbqtAEYzLnoUGNBplBJZigKoFUjwMVtFaUUQqgjJKxRCTYchxKOlwnkLaxRJmQkmWEPXShMuPMVBDyojGtpBCSwegqVwdevwTKQtrstgqRDTNYjoRDBebxDIeAmNXcJtvhGlAEyvovbitelUUEfpsLuzEjSkAnbofHHSUlzBQchPXWeSqbPJIgUuyivXKpxJaAEzLiBOzxueTGfvqGKebsOTtIJUNvGIQbNpWHrsIFeopBQuWUvtwOUOefADqmRxwpKrpJkPPgPbTYxxaVStLUrvvpqplkyrYVQqfZfrxzqRrFPuuRVzZmxTJoDFmthqRIBGezJVHtXCzOxhXjGafTlrNsRcrYecounGZiREdAxVJqKtZULRHoGUrSOOrXSNuFQpmshCMPourVxOfPXjEfHLqVsDJqYGQmvDJxkhAlpwzpcQxIgXLqsXjzQVQIrQpgzNASbitKgjNZXgQGgxidbrnDFFrMEliRKyrcnAtFFfklKwWHCCANBpINxmcBUdrGYAgAjucbfbCvPfBVNsqeVELHbVYaIFMbwLfNDWdJVZYrsoTYuROQXeXVuHIY",
    "625": "lUtJeAxEQwijOcYMLmOtsacHeBeZSdIUJJjAboavTdYwloonaQCXfHRyDMOZtNBlsQsRunrRRJVPioBYYxIgyeFsSXlxOVdFVIAKKJoGtYRmYGgUfgdCZFCYycViiEjZEmeQBnGxqfFUOaodwNyKUNenIXDlIoWhEHfPUGQMoAHfBVxiabrEOqnehypedITaBMCuNJTWBEAXlzgnOMQIhPbLzdKkIsyayZBmwAEqWsKQucPNkSVISVSZRFbUDqPBJkJzvCgijHpQBuqXZksJDbzeVreSeOqWfItxFuOBmeRqAdefTVucpocKhtepRVoyfVESIkqsNsNanDHgicRWPlAKTWRIGkgDPOjFBZVmaCYHBekUgvydLWvDuodPadnuPUmEavZQSIASNMIBSAmKArsUkkBOMIDNQzrlWzDYywnDEOfzWqJzmOaESBtTrJEzHbCIKIqyGeneBblVGtCKidNmaOFQMvMtvmmhAtcjWpwRZzwuPSihEOSNIJgbmdrPgMfUoWFWobCZMGbqUmOHmJwArZmwvZBUSynheNuzbOBAXbEjvAlnBFFFMvIfrbGviAvjqyRrAALfoeIGtGpPJcYOgSlgsUBUymWQUhflCkUtsReLICymEAnyrepBPtrkPgKvVGbgSbjHhExDvKOFiVuCVDepQMjDDoQlsYygsjbYkgLuwNZljwbBnnFMbsuKgtuFrvqNmhZbzjoqqGAbbXINvLDPsJhcfhsXAzbWqlwXaHGOctmvjEwagCKLiqDJ",
    "3125": "DaMqMuovfwNMwbmpthrxtNXoXvgeAZvQkaszslWLGYYLTVhfaIgpcHeuwcFdOFfmezRLVkmMbqAfctdmFvaJEJKkFQaLPCAFvlBQTxQCwvIaLfJByMPTkHnYxmolynJhGPVYSUaXwoNHPVWCHUFsIMUuWJawynjiTEOIqVrmsyYMGHzYajzhogKfCKFheErlJfFnEMIorMoMKgcLehJjrqPncLOvvdlzBHQGIpVroNuxtnEDIrvjahFWdIlaxXcdwypuCwBthXSYooypBoHNtBiyTUaozbcVjXUYlXjrNFRfhxJZIqsIPiksnOaNmekpISdIYBineyMIbGhQINNWoTdTcUiPLrieMGIxDFKVVDNJQrgCKcNRVRaaroQqBDiJCjHsPLkuHmamOgIZexWZiLWqZtbfjaHOthOBgOEQgKZdIsxPzgyfjOWCMmdmNJgQtpXfCSzqBgWikJhDGLbdjZJtjWzkFiZlHykaHbCPaGdffxrNITcUssHCLnkoBdBIEsUdjJMcsxcggOFDCmNWkBOYJfvBWJzHmuUFqgQjIuGZXSXlMMDvUPpqBQMeVMMrpFfznSvmwdQzMyqkCjPIYZGCcXUGldvMwuPNSJFNyXzLcyYvugpmSPMrAhJhmArBtUedsDxgngZmnivvSnhMLFejGyTKxskjPagphmiltghsuRvfSKuGRStKUptzbPzhZCBbrEOVteipXXNhzStpkRsbcTlqfoHleAnxlOBIQNrXWwiGeUySpMpgeZkwGnMX",
    "15625": "AVneHHavyaxnwhoUVQVpiYLcTskxwXXCVItGmUOotjsookwArqaQwnELxFMvmwJnAXDUAiVAKqwtAieLZcPZDmIZayTkdJUUNrQJNJOpbQcOROFJPzLJRZIHeMbJVjafqYHEwLjscutoVZXswzAHvGGgRZOvbGrwlGdSRPLcNqfRkTXfNsQBsAbjXJLesmPcZngwPCRlZTUFuQgtmRVMmfjdyXqDpRNcxDbGbvXjkMuPLkWzyZkvLLgOuQlENnjFcRSrCsWeJlrdZDGbAlWnFAAnjAShRzYFfBLdrMFvcBlaWKCznigvtGLeolYzIFqEptDDGOBoNDXcPDCbNMpwDsoLOlvigebtuDrQtZymkSZvgVJdBNdWmkGcCrWuXSsuWghaFVkysxoBJTzSueQwOQTkxzpyDiXJwQtoGvzpyWxqViNdIKbiDkBflctyULEfyKAwIzEQXilbvguWQvblusIOcQkxdshzdmSkSfQLuYPBdBtFmHuozWFEFfOQaLPDsSuvfUYrQMmaiNPPwVMwRBeQpkHchnfJMLMNDHFeuMQShnYbhTvvWzWjLrovfNWzIYASaATRaDisoDGEsSkScIxdsFaLcjAlVMIJmYDbHyTCKIakfaSgWaXnQzMWVSeJGWfAiwnErxddFODtoGReVlUjJPHwizJDnoAbLGaizsMJbInOOXXvdjqaGuqkXcwGlTnhvOwZxanYFPXhILaMknqQotGNmiAfLbqcMBhxTBDyZECrRiJjHqhpiisWudul",
    "78125": "aCeezKLBFwSSstzwiDaIJxWvyzohGpMVxFYMhjaHUbaQbTMKGFecutmDMpfoeyRobLagGOXgKQnqkRSrMbwMAIaekSpduEvhKOKnLTLbRYjAwqXFqTRSgMyplDWKjzEewbHTVFMNVwIkKITRvuWpCBihiYpmPtpqybqAhmTnACgksbisHCcSINjqEvjkfvqVXCZNGzXsCTsPOedbPYRePZaYIeNoloZeUjVlDDhIKbREhIuIihhOCZIGfPMZFBOMjQwnnHbrpeTrCfGetFiLdGFUuAjGDsGgCkBvKonDOfdSxbwOyRvBKrTPwbSYLPZqDkxZdvlfyqcGkiRtnPlTjvgEhCzVgUwcmxRPayMBTYwLMsVaiDBsujmISibdOGPVLKMpruJRMbYiUuvVsUgkSedHtZJAcKNKlwBojEpKpopQNAwHJnvHedSBhHcCdIAHRGKQzNYUmyKKPuEcnjQxTbLwaDUYWmnmuMIYjqfRZqwfRbnnxeihiCPUTmyXgUldQQfwBLGxUCbrUzftpZobaxFfqUmqykYAlEuEKZjmuzjWBEZthJZXfujobCYVLPtRTZXREcoyiilwHjDfMzbuSwpnPCXDmGpSEvcRphWpzdrlSgBXEwdLtFuQhBfDvfCEGjEjmplXacLnylaPKfcUIQOIQngGNSHVMStvFbnGsdkABCmyZELlPGoQineWOHLIJnsOinyZvGBGeFFwtdPpZruXpKrbopPqyzfvBaPgXChHogkedHljkrisXGoxkZHN",
    "390625": "aThwXRHjFYxssnKxgNddIIDDFIZOuXcVbuYwLeBtZsoTYGrUyXcpxFNqFrqdzXEKHSorjCZryNULqZpAJPWyApNGFGKWtRREuAiKXBVJCnPpVbwhitTSVNhITRSphpLQZjpYVPUOYiZOWSXuUDOVxsZgUXYpcpycFliknqMxufCRapLgwJsyfGYlwScdOlOUvPynXqpksIDSXmaPBEFXtIJqPTAHeEDMQriCKRGXUjeuTKTvcFleVEiApmjyCUtICHMBPCxuGmzquMophQXILoSRXERnckNMLluJMZqylKTNtovKOvkBhoFhrRxCCVzKydYhjfqMrwtkFRVSrnBKRnnEujnDNSsFKpkCkSVKghniIAFHpvvofqzhOdqmGmUBzTdcmLaBXnsQAFzBQlcwzkfxsFKSRzASlGnmQskeZtXNNlyqXmAoykuDXJahITEPRGrANrOaZFXNtpWifKVoRDLrPTzjiMTkIrLRCrldvqcqXnjaObYPQouOayxFpRgGnxecIwBxwzfuxNgdLcJPTHZRKPaTmscGkuvDwYDhYdJobZlaZZbbETLuscvBmmTvgpehBDtPqjNEmCCGDgGeLgVfMVsWcmdYRpWBHQlvWMaYdpiOUmbwRuskUlHLcEbdAmcLzLiCVqqeBBJxlxXZKzcKzZFLYAQRiymZSqgnQCGFwcPeFBVBgPigpAqcEjQjMqYvSGvubRVHrLnTaylLeKzBrLWiIKLAzyiBYuEKOCpMsUaufaWIYEvRlMAzOCuY",
}

table_size = sys.argv[1]
if table_size not in supported_table:
    print(f"Invalid table size. supported table: {supported_table.keys()}")
    raise Exception
round = int(sys.argv[2])
sql_id = int(sys.argv[3])

table = f"{table_size}_big_pk_test"
print(f"Test Job: count * test. Table: {table}")

sql = {
    1: f"select * from {table} where big_pk = \"{supported_table[table_size]}\"",
}

# Connect to MySQL server
conn = mysql.connector.connect(**db_cred)

# Create cursor
cursor = conn.cursor()
total_time = 0

for i in range(round):
    start = time.perf_counter()
    cursor.execute(sql[sql_id])
    data = cursor.fetchall()
    end = time.perf_counter()
    print(f"select_time: {end-start}, round: {i}")
    total_time += end-start
print(f"Total_round: {round}, avg_time: {total_time/round}")

# Commit changes and close connection
conn.commit()
conn.close()

print("Done selecting data")
